spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/library_bd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: its.amalia.romanenko@gmail.com
    password: xprqvpunkszfgzys
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  sql:
    init:
      mode: always
token:
  jwt:
    secretKey: "somesecretkey"
    validTime: 247000
